packages:
  - packages/*

catalog:
  next: ^16
  eslint-config-next: ^16
  '@next/eslint-plugin-next': ^16
  react: ^19.2.0
  react-dom: ^19.2.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1
  typescript: ^5.9.3
  eslint: ^9.37.0
  '@types/node': ^22.18.9
  babel-plugin-react-compiler: ^1.0.0
  '@vitejs/plugin-react': ^5.1.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.8

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - bufferutil
  - cbor-extract
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
