packages:
  - "packages/*"

catalog:
  next: ^15.3.3
  eslint-config-next: ^15.3.3
  '@next/eslint-plugin-next': ^15.3.1
  react: ^19.0.0
  react-dom: ^19.0.0
  '@types/react': ^19
  '@types/react-dom': ^19
  typescript: ^5.8.3
  eslint: ^9
  '@types/node': ^22
