packages:
  - packages/*

catalog:
  next: ^15.4.1
  eslint-config-next: ^15.4.1
  "@next/eslint-plugin-next": ^15.4.1
  react: ^19.1.0
  react-dom: ^19.1.0
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  typescript: ^5.8.3
  eslint: ^9.31.0
  "@types/node": ^22.16.4
