packages:
  - packages/*

catalog:
  next: 15.5.1-canary.22
  eslint-config-next: ^15.5.0
  '@next/eslint-plugin-next': ^15.5.0
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  typescript: ^5.8.3
  eslint: ^9.31.0
  '@types/node': ^22.16.4
  babel-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-compiler: 19.1.0-rc.2
