packages:
  - "packages/*"

catalog:
  next: ^15.3.0
  eslint-config-next: ^15.3.0
  '@next/eslint-plugin-next': ^15.3.0
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.8.3
  eslint: ^9
  '@types/node': ^22
