packages:
  - packages/*

catalog:
  next: ^16.0.7
  eslint-config-next: ^16
  '@next/eslint-plugin-next': ^16
  react: ^19.2.1
  react-dom: ^19.2.1
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1
  typescript: ^5.9.3
  eslint: ^9.37.0
  '@types/node': ^22.18.9
  babel-plugin-react-compiler: ^1.0.0
  '@vitejs/plugin-react': ^5.1.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.8
  '@atproto/repo': ^0.8.10
  '@atproto/syntax': ^0.3.4
  '@atproto/identity': ^0.4.9
  '@atproto/did': ^0.2.1
  '@atproto/api': ^0.18.0

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - bufferutil
  - cbor-extract
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
