# fly.toml app configuration file generated for bluesky-pds-fly on 2024-06-01T23:31:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bluesky-pds-fly'
primary_region = 'ams'

[build]

[env]
LOG_ENABLED = 'true'
PDS_BLOBSTORE_DISK_LOCATION = '/pds/blocks'
PDS_BSKY_APP_VIEW_DID = 'did:web:api.bsky.app'
PDS_BSKY_APP_VIEW_URL = 'https://api.bsky.app'
PDS_CRAWLERS = 'https://bsky.network'
PDS_DATA_DIRECTORY = '/pds'
PDS_DID_PLC_URL = 'https://plc.directory'
PDS_HOSTNAME = 'pds.tom-sherman.com'
PDS_REPORT_SERVICE_DID = 'did:plc:ar7c4by46qjdydhdevvrndac'
PDS_REPORT_SERVICE_URL = 'https://mod.bsky.app'

[[mounts]]
source = 'pds_data'
destination = '/pds'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
