[package]
name = "drainpipe-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3.26"
drainpipe-store = { path = "../drainpipe-store" }
dotenv-flow = "0.16.2"
chrono = "0.4.42"
serde_json = "1.0.145"
